export const demoProjectsResponse = {
  statusCode: 200,
  message: "Success",
  data: [
    {
      id: "65f1a2c8b4d9f001e8a1a001",
      title: "Portfolio Website v2",
      description:
        "A modern developer portfolio built with Next.js, TailwindCSS and Framer Motion. Includes dark mode, animations and project showcase.",
      coverImage:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
      projectUrl: "https://portfolio-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/portfolio-v2",
      startDate: new Date("2024-01-10"),
      endDate: new Date("2024-02-15"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-16"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [
        {
          id: "media1",
          url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
          type: "IMAGE",
        },
      ],
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-02-16"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a002",
      title: "E-Commerce Admin Dashboard",
      description:
        "Full-stack admin dashboard for managing products, orders and analytics. Built with MERN stack and Chart.js for data visualization.",
      coverImage:
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
      projectUrl: "https://admin-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ecommerce-dashboard",
      startDate: new Date("2024-03-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-03-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "Node.js", "MongoDB", "Express", "Chart.js"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-10"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a003",
      title: "Realtime Chat Application",
      description:
        "Socket.io powered realtime chat app with authentication, typing indicators and online presence tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/realtime-chat",
      startDate: new Date("2023-11-20"),
      endDate: new Date("2024-01-05"),
      isOngoing: false,
      visibility: "PRIVATE",
      publishStatus: "DRAFT",
      publishTime: null,
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Node.js", "Socket.io", "JWT", "MongoDB"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-11-20"),
      updatedAt: new Date("2024-01-05"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a004",
      title: "AI Image Generator",
      description:
        "Text-to-image generation app using diffusion models and serverless inference. Supports prompt history and image downloads.",
      coverImage:
        "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba",
      projectUrl: "https://ai-image-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ai-image-generator",
      startDate: new Date("2024-04-01"),
      endDate: new Date("2024-05-20"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-05-21"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "OpenAI API", "Cloudinary", "TailwindCSS"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [
        {
          id: "media4",
          url: "https://images.unsplash.com/photo-1547658719-da2b51169166",
          type: "IMAGE",
        },
      ],
      createdAt: new Date("2024-04-01"),
      updatedAt: new Date("2024-05-21"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a005",
      title: "DevOps CI/CD Pipeline",
      description:
        "Automated CI/CD pipeline with Docker, GitHub Actions and AWS deployment for scalable microservices.",
      coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/devops-pipeline",
      startDate: new Date("2023-09-01"),
      endDate: new Date("2023-11-10"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-11-15"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Docker", "AWS", "GitHub Actions", "Nginx"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2023-11-15"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a006",
      title: "3D Product Configurator",
      description:
        "Interactive 3D product customization tool built with Three.js and React Three Fiber.",
      coverImage:
        "https://images.unsplash.com/photo-1581093588401-22f3b5b8bdb1",
      projectUrl: "https://3d-config-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/3d-configurator",
      startDate: new Date("2024-02-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-10"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Three.js", "React", "WebGL", "Blender"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date("2024-03-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a007",
      title: "Learning Management System",
      description:
        "Full LMS platform with role-based access, course management and real-time progress tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
      projectUrl: "https://lms-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/lms-platform",
      startDate: new Date("2023-05-01"),
      endDate: new Date("2023-08-20"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-08-25"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Node.js", "PostgreSQL", "Redis"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-05-01"),
      updatedAt: new Date("2023-08-25"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a008",
      title: "Expense Tracker App",
      description:
        "Personal finance tracking app with charts, budgeting tools and recurring expense automation.",
      coverImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f",
      projectUrl: "https://expense-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/expense-tracker",
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-02-01"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-02"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "Firebase", "Chart.js"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-02-02"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a009",
      title: "Code Snippet Manager",
      description:
        "Developer tool to store, tag and search reusable code snippets with markdown preview.",
      coverImage:
        "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/snippet-manager",
      startDate: new Date("2023-07-10"),
      endDate: new Date("2023-09-01"),
      isOngoing: false,
      visibility: "PRIVATE",
      publishStatus: "DRAFT",
      publishTime: null,
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Prisma", "Markdown"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-07-10"),
      updatedAt: new Date("2023-09-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a010",
      title: "Fitness Tracking Dashboard",
      description:
        "Health analytics dashboard visualizing workout metrics and calorie tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b",
      projectUrl: "https://fitness-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/fitness-dashboard",
      startDate: new Date("2024-03-15"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-03-20"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "D3.js", "MongoDB"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-03-15"),
      updatedAt: new Date("2024-04-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a011",
      title: "Task Automation Bot",
      description:
        "Automation bot that integrates with Slack and Notion for workflow optimization.",
      coverImage:
        "https://images.unsplash.com/photo-1581091215367-59ab6c1f0c9b",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/automation-bot",
      startDate: new Date("2023-12-01"),
      endDate: new Date("2024-01-10"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-01-15"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Node.js", "Slack API", "Notion API"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-12-01"),
      updatedAt: new Date("2024-01-15"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a012",
      title: "Online Code Judge",
      description:
        "Competitive programming platform with custom test cases and real-time code execution.",
      coverImage:
        "https://images.unsplash.com/photo-1517433456452-f9633a875f6f",
      projectUrl: "https://codejudge-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/code-judge",
      startDate: new Date("2023-06-01"),
      endDate: new Date("2023-10-01"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-10-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Docker", "Node.js", "Redis"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-06-01"),
      updatedAt: new Date("2023-10-05"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a013",
      title: "AR Furniture Preview App",
      description:
        "Augmented reality web app allowing users to preview furniture in their space using WebXR.",
      coverImage:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
      projectUrl: "https://ar-furniture-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ar-furniture",
      startDate: new Date("2024-05-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-05-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["WebXR", "Three.js", "React"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-05-01"),
      updatedAt: new Date("2024-05-10"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a015",
      title: "Portfolio Website v2",
      description:
        "A modern developer portfolio built with Next.js, TailwindCSS and Framer Motion. Includes dark mode, animations and project showcase.",
      coverImage:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
      projectUrl: "https://portfolio-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/portfolio-v2",
      startDate: new Date("2024-01-10"),
      endDate: new Date("2024-02-15"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-16"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [
        {
          id: "media1",
          url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
          type: "IMAGE",
        },
      ],
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-02-16"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a016",
      title: "E-Commerce Admin Dashboard",
      description:
        "Full-stack admin dashboard for managing products, orders and analytics. Built with MERN stack and Chart.js for data visualization.",
      coverImage:
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
      projectUrl: "https://admin-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ecommerce-dashboard",
      startDate: new Date("2024-03-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-03-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "Node.js", "MongoDB", "Express", "Chart.js"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-10"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a017",
      title: "Realtime Chat Application",
      description:
        "Socket.io powered realtime chat app with authentication, typing indicators and online presence tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/realtime-chat",
      startDate: new Date("2023-11-20"),
      endDate: new Date("2024-01-05"),
      isOngoing: false,
      visibility: "PRIVATE",
      publishStatus: "DRAFT",
      publishTime: null,
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Node.js", "Socket.io", "JWT", "MongoDB"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-11-20"),
      updatedAt: new Date("2024-01-05"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a018",
      title: "AI Image Generator",
      description:
        "Text-to-image generation app using diffusion models and serverless inference. Supports prompt history and image downloads.",
      coverImage:
        "https://images.unsplash.com/photo-1682687220742-aba13b6e50ba",
      projectUrl: "https://ai-image-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ai-image-generator",
      startDate: new Date("2024-04-01"),
      endDate: new Date("2024-05-20"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-05-21"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "OpenAI API", "Cloudinary", "TailwindCSS"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [
        {
          id: "media4",
          url: "https://images.unsplash.com/photo-1547658719-da2b51169166",
          type: "IMAGE",
        },
      ],
      createdAt: new Date("2024-04-01"),
      updatedAt: new Date("2024-05-21"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a019",
      title: "DevOps CI/CD Pipeline",
      description:
        "Automated CI/CD pipeline with Docker, GitHub Actions and AWS deployment for scalable microservices.",
      coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/devops-pipeline",
      startDate: new Date("2023-09-01"),
      endDate: new Date("2023-11-10"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-11-15"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Docker", "AWS", "GitHub Actions", "Nginx"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-09-01"),
      updatedAt: new Date("2023-11-15"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a020",
      title: "3D Product Configurator",
      description:
        "Interactive 3D product customization tool built with Three.js and React Three Fiber.",
      coverImage:
        "https://images.unsplash.com/photo-1581093588401-22f3b5b8bdb1",
      projectUrl: "https://3d-config-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/3d-configurator",
      startDate: new Date("2024-02-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-10"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Three.js", "React", "WebGL", "Blender"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date("2024-03-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a021",
      title: "Learning Management System",
      description:
        "Full LMS platform with role-based access, course management and real-time progress tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
      projectUrl: "https://lms-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/lms-platform",
      startDate: new Date("2023-05-01"),
      endDate: new Date("2023-08-20"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-08-25"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Node.js", "PostgreSQL", "Redis"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-05-01"),
      updatedAt: new Date("2023-08-25"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a022",
      title: "Expense Tracker App",
      description:
        "Personal finance tracking app with charts, budgeting tools and recurring expense automation.",
      coverImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f",
      projectUrl: "https://expense-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/expense-tracker",
      startDate: new Date("2024-01-01"),
      endDate: new Date("2024-02-01"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-02-02"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "Firebase", "Chart.js"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-02-02"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a023",
      title: "Code Snippet Manager",
      description:
        "Developer tool to store, tag and search reusable code snippets with markdown preview.",
      coverImage:
        "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/snippet-manager",
      startDate: new Date("2023-07-10"),
      endDate: new Date("2023-09-01"),
      isOngoing: false,
      visibility: "PRIVATE",
      publishStatus: "DRAFT",
      publishTime: null,
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Prisma", "Markdown"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-07-10"),
      updatedAt: new Date("2023-09-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a024",
      title: "Fitness Tracking Dashboard",
      description:
        "Health analytics dashboard visualizing workout metrics and calorie tracking.",
      coverImage:
        "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b",
      projectUrl: "https://fitness-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/fitness-dashboard",
      startDate: new Date("2024-03-15"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-03-20"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["React", "D3.js", "MongoDB"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-03-15"),
      updatedAt: new Date("2024-04-01"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a025",
      title: "Task Automation Bot",
      description:
        "Automation bot that integrates with Slack and Notion for workflow optimization.",
      coverImage:
        "https://images.unsplash.com/photo-1581091215367-59ab6c1f0c9b",
      projectUrl: null,
      repositoryUrl: "https://github.com/demo/automation-bot",
      startDate: new Date("2023-12-01"),
      endDate: new Date("2024-01-10"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-01-15"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Node.js", "Slack API", "Notion API"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-12-01"),
      updatedAt: new Date("2024-01-15"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a026",
      title: "Online Code Judge",
      description:
        "Competitive programming platform with custom test cases and real-time code execution.",
      coverImage:
        "https://images.unsplash.com/photo-1517433456452-f9633a875f6f",
      projectUrl: "https://codejudge-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/code-judge",
      startDate: new Date("2023-06-01"),
      endDate: new Date("2023-10-01"),
      isOngoing: false,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2023-10-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["Next.js", "Docker", "Node.js", "Redis"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2023-06-01"),
      updatedAt: new Date("2023-10-05"),
    },
    {
      id: "65f1a2c8b4d9f001e8a1a027",
      title: "AR Furniture Preview App",
      description:
        "Augmented reality web app allowing users to preview furniture in their space using WebXR.",
      coverImage:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
      projectUrl: "https://ar-furniture-demo.vercel.app",
      repositoryUrl: "https://github.com/demo/ar-furniture",
      startDate: new Date("2024-05-01"),
      endDate: null,
      isOngoing: true,
      visibility: "PUBLIC",
      publishStatus: "PUBLISHED",
      publishTime: new Date("2024-05-05"),
      ownerId: "65f1a2c8b4d9f001e8a1owner1",
      skills: ["WebXR", "Three.js", "React"],
      likes: [],
      comments: [],
      tags: [],
      wishlistEntries: [],
      projectMedias: [],
      createdAt: new Date("2024-05-01"),
      updatedAt: new Date("2024-05-10"),
    },
  ],
};
